### ISSUE TITLE
[storage-extract-image-text] Fails if storage bucket not already created. Uninstall not available.

### ISSUE THREAD

**Issue by PaulTR** [FirebaseExtended/experimental-extensions#45]
## Expected Behavior
I'd like to see the extension initialize the default storage bucket if it isn't already there. If not, then I'd like an uninstall/reinstall button to be available. Using the reconfigure option installs correctly after initializing storage.

- Extension name: Image Text Extraction
- Version: 0.0.3

**Comment by i14h** [comment]
Hey Paul, thanks for the feedback. Yes initializing resources before install is something we're looking to implement on the backend but a bit complicated due to GCF limitations and the fact that it'll add 5-10 mins to the install time for all extensions. 
For uninstall there's at the bottom of the extension details page, does that work for you?

**Comment by PaulTR** [comment]
The uninstall button wasn't there at all in the error state.

**Comment by i14h** [comment]
I'm assuming this is resolved. Paul if the issue still persists let us know.
